on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Sleep for 30 seconds
      run: Start-Sleep -s 60
      shell: powershell
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium webdriver-manager
